### PR TITLE
Update with juliandescottes fork

### PR DESCRIPTION
**Pull request by caleybrock**
Goal: Don't fall behind upstream and get latest performance improvements.
did a `git merge upstream/master`

Updating piskel gets us lots of performance improvements and bug fixes. We get v 0.5.5 - v 0.10.0 with this PR.
https://github.com/juliandescottes/piskel/releases

See the last 5 follow up commits that I pushed where I modified/removed code so that our use cases work:
- don't take copy paste changes because we have our own version of copy/paste now
- remove use of piskelController to set fps because this was removed in code upstream
- remove browser warning popups
- fix ImportServiceTest

Manually tested editing, saving, adding frames, resizing, etc within gamelab on IE, Firefox, and Chrome.

Next I'll see what makes sense to push upstream.

### CODE REVIEW

**Comment by islemaster** [comment]
Wow, that's a huge changeset!  I didn't realize we were so far behind.  I likely won't be able to review today, but will start in on this tomorrow morning.

**Comment by caleybrock** [comment]
No worries, there isn't a rush on this. I'd say focus on the last few commits I added because those are the changes that make the upstream changes compatible.

Also if it helps this is where I got merge conflicts that I had to manually resolve:
screen shot 2017-02-15 at 4 38 19 pm

**Comment by caleybrock** [comment]
I also realized almost none of our changes are upstream (including PiskelAPI files) so it'll be a non-trivial amount of work to figure out what should go upstream and add tests. I'm going to look at breaking this up a little over sprints.

**Review by islemaster — APPROVED** [review]
This looks really good.  Hooray for Travis tests!  How much manual testing do you think we should be doing on this before the merge?

As to submitting changes upstream, [here's a diff of everything we've added](https://github.com/juliandescottes/piskel/compare/master...code-dot-org:merge-with-upstream) and I don't think it's as bad as it looks from the commit list.  I think submitting PiskelAPI itself, with some tests and maybe an 'embedded piskel' example, would probably go over well.

**Comment by juliandescottes** [comment]
> As to submitting changes upstream, here's a diff of everything we've added and I don't think it's as bad as it looks from the commit list. I think submitting PiskelAPI itself, with some tests and maybe an 'embedded piskel' example, would probably go over well.

Definitely in favor of getting as much as we can to Piskel (or to define clear APIs) so that the sync process can be easier for you in the future!

**Comment by caleybrock** [comment]
Agreed, pushing our `PiskelAPI` upstream will make the biggest difference in making syncs easier - it's my next priority for piskel work. Plus the more tests I add the more comfortable I think I'll be leaving out some manual testing 👍

**Pull request merged**
